version: "3.9"

services:
  db:
    build: postgres
  publisher:
    build: publisher
    depends_on:
      - db
  consumer-a:
    build: consumer
    depends_on:
      - db
  consumer-b:
    build: consumer
    depends_on:
      - db
  consumer-c:
    build: consumer
    depends_on:
      - db
  consumer-d:
    build: consumer
    depends_on:
      - db
  consumer-e:
    build: consumer
    depends_on:
      - db
